CREATE TABLE IF NOT EXISTS lancamentos_financeiros
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo         VARCHAR(20)    NOT NULL,
    categoria    VARCHAR(30)    NOT NULL,
    descricao    VARCHAR(255)   NOT NULL,
    valor        DECIMAL(10, 2) NOT NULL,
    data         TIMESTAMP      NOT NULL,
    pagamento_id BIGINT,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at   TIMESTAMP,

    CONSTRAINT fk_lancamento_pagamento FOREIGN KEY (pagamento_id) REFERENCES pagamentos (id)
);

CREATE INDEX idx_lancamento_data ON lancamentos_financeiros (data);
CREATE INDEX idx_lancamento_pagamento ON lancamentos_financeiros (pagamento_id);
