CREATE TABLE IF NOT EXISTS agendamentos
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id      BIGINT    NOT NULL,
    data_hora   TIMESTAMP NOT NULL,
    status      VARCHAR(50),
    valor_total DECIMAL(10, 2),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_agendamento_pet FOREIGN KEY (pet_id) REFERENCES pets (id) ON DELETE CASCADE
);

CREATE INDEX idx_agendamento_pet ON agendamentos (pet_id);
CREATE INDEX idx_agendamento_data ON agendamentos (data_hora);
