CREATE TABLE IF NOT EXISTS historico_pets
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id       BIGINT NOT NULL,
    data         TIMESTAMP,
    tipo_servico VARCHAR(100),
    notas        TEXT,
    preco_pago   DECIMAL(10, 2),

    CONSTRAINT fk_historico_pet FOREIGN KEY (pet_id) REFERENCES pets (id) ON DELETE CASCADE
);

CREATE INDEX idx_historico_pet ON historico_pets (pet_id);

