CREATE TABLE IF NOT EXISTS enderecos
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cep         VARCHAR(8)   NOT NULL,
    logradouro  VARCHAR(150) NOT NULL,
    numero      VARCHAR(6),
    complemento VARCHAR(100),
    bairro      VARCHAR(150) NOT NULL,
    cidade      VARCHAR(150) NOT NULL,
    estado      VARCHAR(2)   NOT NULL
);

ALTER TABLE tutores ADD COLUMN endereco_id BIGINT;

INSERT INTO enderecos (cep, logradouro, numero, complemento, bairro, cidade, estado)
SELECT cep, logradouro, numero, complemento, bairro, cidade, estado
FROM tutores
ORDER BY id;

UPDATE tutores
SET endereco_id = (
    SELECT e.id
    FROM (
        SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn FROM tutores
    ) t
    JOIN (
        SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn FROM enderecos
    ) e ON e.rn = t.rn
    WHERE t.id = tutores.id
);

ALTER TABLE tutores ALTER COLUMN endereco_id SET NOT NULL;

ALTER TABLE tutores ADD CONSTRAINT uk_tutor_endereco UNIQUE (endereco_id);

ALTER TABLE tutores ADD CONSTRAINT fk_tutor_endereco
    FOREIGN KEY (endereco_id) REFERENCES enderecos (id) ON DELETE CASCADE;

ALTER TABLE tutores DROP COLUMN cep;
ALTER TABLE tutores DROP COLUMN logradouro;
ALTER TABLE tutores DROP COLUMN numero;
ALTER TABLE tutores DROP COLUMN complemento;
ALTER TABLE tutores DROP COLUMN bairro;
ALTER TABLE tutores DROP COLUMN cidade;
ALTER TABLE tutores DROP COLUMN estado;